-- AlterTable
ALTER TABLE `Church` ADD COLUMN `websiteStatus` ENUM('NONE', 'PENDING', 'DEPLOYING', 'LIVE', 'FAILED') NOT NULL DEFAULT 'NONE',
    ADD COLUMN `websiteUrl` VARCHAR(191) NULL,
    ADD COLUMN `customDomain` VARCHAR(191) NULL,
    ADD COLUMN `vercelProjectId` VARCHAR(191) NULL,
    ADD COLUMN `vercelDeploymentId` VARCHAR(191) NULL,
    ADD COLUMN `mobilePlan` ENUM('SHARED', 'WHITELABEL') NOT NULL DEFAULT 'SHARED',
    ADD COLUMN `mobileBuildStatus` ENUM('NONE', 'QUEUED', 'BUILDING', 'SUBMITTED', 'LIVE', 'FAILED') NOT NULL DEFAULT 'NONE';
